apiVersion: v1
kind: Namespace
metadata:
  name: temporalize

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporalize-web
  namespace: temporalize
  labels:
    app: temporalize
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: temporalize-web
  template:
    metadata:
      labels:
        app: temporalize-web
    spec:
      containers:
      - name: temporalize
        image: docker-registry.service:30000/temporalize:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "30Mi"
            cpu: "50m"

---

apiVersion: v1
kind: Service
metadata:
  name: temporalize-web
  namespace: temporalize
spec:
  selector:
    app: temporalize
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000

---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: temporalize
  namespace: temporalize
spec:
  ingressClassName: haproxy
  rules:
    - host: temporalize.jacobbaldwin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: temporalize-web
                port:
                  number: 8000
status:
  loadBalancer:
    ingress:
      - {}